# Pipeline name convention
name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

# Trigger configuration
trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

# Parameters
parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

# Resources
resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: pl-709   # Optional: build with a specific pipeline version

# Pipeline template
extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs   # Optional: nodejs (default), dotnet, java
    Type: kubernetes           # Optional: kubernetes (default), npm, functions, nuget
    npmLegacyPeerDeps: false   # Optional: default is false
    dockerFilePath: Dockerfile # Optional default is Dockerfile
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    # failOnThreshold: moderate
    variableGroupName: ffc-pay-batch-processor-env-var
    pr_params:
      pollingInterval: $(pr_pollingInterval)
      maxProcessingTries: $(pr_maxProcessingTries)
      disableSequenceValidation: $(pr_disableSequenceValidation)
    snd2_params:
      pollingInterval: $(snd2_pollingInterval)
      maxProcessingTries: $(snd2_maxProcessingTries)
      disableSequenceValidation: $(snd2_disableSequenceValidation)
    dev_params:
      pollingInterval: $(dev_pollingInterval)
      maxProcessingTries: $(dev_maxProcessingTries)
      disableSequenceValidation: $(dev_disableSequenceValidation)
    test_params:
      pollingInterval: $(test_pollingInterval)
      maxProcessingTries: $(test_maxProcessingTries)
      disableSequenceValidation: $(test_disableSequenceValidation)
    pre_params:
      pollingInterval: $(pre_pollingInterval)
      maxProcessingTries: $(pre_maxProcessingTries)
      disableSequenceValidation: $(pre_disableSequenceValidation)
    prod_params:
      pollingInterval: $(prod_pollingInterval)
      maxProcessingTries: $(prod_maxProcessingTries)
      disableSequenceValidation: $(prod_disableSequenceValidation)