# Pipeline name convention
name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

# Trigger configuration
trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

# Parameters
parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

# Resources
resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: pl-709   # Optional: build specific pipeline branch

# Pipeline template
extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs   # Optional: nodejs (default), dotnet, java
    Type: kubernetes           # Optional: kubernetes (default), npm, functions, nuget
    npmLegacyPeerDeps: false   # Optional: default is false
    dockerFilePath: Dockerfile # Optional default is Dockerfile
    failOnThreshold: moderate  # Optional: moderate (default), low, high, critical
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    variableGroupName: ffc-pay-batch-processor-env-var
    pr_params:
      container.pollingInterval: $(pr_pollingInterval)
      container.maxProcessingTries: $(pr_maxProcessingTries)
      container.disableSequenceValidation: ${{ eq(variables['pr_disableSequenceValidation'], 'true') }}
      container.processingActive: ${{ eq(variables['pr_processingActive'], 'true') }}
    snd2_params:
      container.pollingInterval: $(snd2_pollingInterval)
      container.maxProcessingTries: $(snd2_maxProcessingTries)
      container.disableSequenceValidation: ${{ eq(variables['snd2_disableSequenceValidation'], 'true') }}
      container.processingActive: ${{ eq(variables['snd2_processingActive'], 'true') }}
    dev_params:
      container.pollingInterval: $(dev_pollingInterval)
      container.maxProcessingTries: $(dev_maxProcessingTries)
      container.disableSequenceValidation: ${{ eq(variables['dev_disableSequenceValidation'], 'true') }}
      container.processingActive: ${{ eq(variables['dev_processingActive'], 'true') }}
    test_params:
      container.pollingInterval: $(test_pollingInterval)
      container.maxProcessingTries: $(test_maxProcessingTries)
      container.disableSequenceValidation: ${{ eq(variables['test_disableSequenceValidation'], 'true') }}
      container.processingActive: ${{ eq(variables['test_processingActive'], 'true') }}
    pre_params:
      container.pollingInterval: $(pre_pollingInterval)
      container.maxProcessingTries: $(pre_maxProcessingTries)
      container.disableSequenceValidation: ${{ eq(variables['pre_disableSequenceValidation'], 'true') }}
      container.processingActive: ${{ eq(variables['pre_processingActive'], 'true') }}
    prd_params:
      container.pollingInterval: $(prd_pollingInterval)
      container.maxProcessingTries: $(prd_maxProcessingTries)
      container.disableSequenceValidation: ${{ eq(variables['prd_disableSequenceValidation'], 'true') }}
      container.processingActive: ${{ eq(variables['prd_processingActive'], 'true') }}
