version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfi-payment-batch-processor:
    build:
      target: development
    depends_on:
      - azurite
    image: ffc-sfi-payment-batch-processor-development
    container_name: ffc-sfi-payment-batch-processor-development
    ports:
      - "9237:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: ffc-sfi-payment-batch-processor-azurite
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    volumes:
      - azurite_data:/data
    ports:
      - "10000:10000"

volumes:
  azurite_data:
