version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfi-payment-batch-processor:
    build:
      target: development
    image: ffc-sfi-payment-batch-processor-development
    container_name: ffc-sfi-payment-batch-processor-development
    ports:
      - "9237:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
