version: '3.8'

services:
  ffc-sfi-payment-batch-processor:
    build:
      context: .
      target: production
    image: ffc-sfi-payment-batch-processor
    container_name: ffc-sfi-payment-batch-processor
    depends_on:
      - ffc-sfi-payment-batch-processor-postgres
    environment:
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      PAYMENT_TOPIC_ADDRESS: ${PAYMENT_TOPIC_ADDRESS:-notset}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      POLLING_INTERVAL: ${POLLING_INTERVAL}
      MAX_PROCESSING_TRIES: ${MAX_PROCESSING_TRIES:-notset}
      POSTGRES_DB: ffc_sfi_payment_batch_processor
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-sfi-payment-batch-processor-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}

  ffc-sfi-payment-batch-processor-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_sfi_payment_batch_processor
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
