version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfi-payment-batch-processor:
    build:
      target: development
    depends_on:
      - ffc-sfi-payment-batch-processor-azurite
      - ffc-sfi-payment-batch-processor-postgres
    image: ffc-sfi-payment-batch-processor-development
    container_name: ffc-sfi-payment-batch-processor-development
    ports:
      - "9237:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
    environment:
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-sfi-payment-batch-processor-azurite:10000/devstoreaccount1;

  ffc-sfi-payment-batch-processor-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: ffc-sfi-payment-batch-processor-azurite
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    volumes:
      - azurite_data:/data
    ports:
      - "10000:10000"

  ffc-sfi-payment-batch-processor-postgres:
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  azurite_data:
  postgres_data:
