version: '3.8'

services:
  ffc-sfi-payment-batch-processor:
    build:
      context: .
      target: production
    image: ffc-sfi-payment-batch-processor
    container_name: ffc-sfi-payment-batch-processor
    environment:
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
