services:
  ffc-pay-batch-processor:
    build:
      context: .
      target: production
    image: ffc-pay-batch-processor
    container_name: ffc-pay-batch-processor
    depends_on:
      - ffc-pay-batch-processor-postgres
      - ffc-pay-batch-azurite
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-batch-processor-local
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      PAYMENT_TOPIC_ADDRESS: ${PAYMENT_TOPIC_ADDRESS:-ffc-pay-request}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_CREATE_CONTAINERS: "true"
      POLLING_INTERVAL: ${POLLING_INTERVAL:-10000}
      MAX_PROCESSING_TRIES: ${MAX_PROCESSING_TRIES:-3}
      POSTGRES_DB: ffc_pay_batch_processor
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-pay-batch-processor-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      EVENT_TOPIC_ADDRESS: ${EVENT_TOPIC_ADDRESS:-ffc-pay-event}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_TOPIC_ADDRESS: ${EVENTS_TOPIC_ADDRESS:-ffc-pay-events}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-pay-batch-azurite:10000/devstoreaccount1;

  ffc-pay-batch-processor-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_pay_batch_processor
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres

  ffc-pay-batch-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.32.0
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    labels:
      com.docker.compose.pay.role: ffc-pay-batch-azurite
