apiVersion: v2
description: FFC Payment Batch Processor
name: ffc-pay-batch-processor
# this version is automatically updated in the build pipline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 4.7.6
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
