environment: development
name: ffc-pay-batch-processor
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-batch-processor

labels: {}

appInsights:
  key:

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-pay-batch-processor-config-map

containerSecret:
  name: ffc-pay-batch-processor-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  # DO NOT have more than 1 replica
  # Payment batch files need to be processed in order
  # So concurrent processing with multiple pods could cause problems
  replicas: 1
  minReplicas: 1
  maxReplicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 100Mi
  requestCpu: 60m
  limitMemory: 100Mi
  limitCpu: 120m
  port: 3007
  azureStorageAccountName: ffcpay
  messageQueueHost: namespace.servicebus.windows.net
  paymentTopicAddress: ffc-pay-request
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  pollingInterval: 60000
  maxProcessingTries: 3

postgresService:
  postgresDb: ffc_pay_batch_processor
  postgresExternalName:
  postgresHost: ffc-pay-batch-processor-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

livenessProbe:
  path: /healthz
  port: 3007
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3007
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

aadPodIdentity: true