environment: development
environmentCode:
name: ffc-pay-batch-processor
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-batch-processor

labels: {}

appInsights:
  connectionString:

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-pay-batch-processor-config-map

containerSecret:
  name: ffc-pay-batch-processor-container-secret
  type: Opaque

deployment:
  # DO NOT have more than 1 replica
  # Payment batch files need to be processed in order
  # So concurrent processing with multiple pods could cause problems
  minReplicas: 1
  maxReplicas: 1

container:
  requestMemory: 100Mi
  requestCpu: 60m
  limitMemory: 200Mi
  limitCpu: 200m
  azureStorageAccountName: ffcpay
  messageQueueHost: namespace.servicebus.windows.net
  paymentTopicAddress: ffc-pay-request
  eventTopicAddress: ffc-pay-event
  eventsTopicAddress: ffc-pay-events
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  pollingInterval: 10000
  maxProcessingTries: 500
  disableSequenceValidation: false
  useV1Events: true
  useV2Events: true
  handleDueDateDefect: true

postgresService:
  postgresDb: ffc_pay_batch_processor
  postgresqlHost: ffc-pay-batch-processor-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

aadPodIdentity: true
