---
environment: production
environmentCode: prd
container:
  messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
  azureStorageAccountName: prdffcpayst1001
  paymentTopicAddress: ffc-pay-request
  eventsTopicAddress: ffc-pay-events
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
secretProviderClass:
  azure:
    keyvaultName: PRDFFCINFKV1001
    objects:
      - objectName: prd-ffcahwr-appInsights-connectionString
        objectType: secret

  secretObjects:
    - secretName: ffc-pay-batch-processor
      type: Opaque
      data:
        - objectName: prd-ffcahwr-appInsights-connectionString
          key: APPINSIGHTS_CONNECTION_STRING
