---
environment: production
environmentCode: prd
container:
  messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
  processingActive: true
  azureStorageAccountName: prdffcpayst1001
  paymentTopicAddress: ffc-pay-request
  eventsTopicAddress: ffc-pay-events
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  pollingInterval: 10000
  maxProcessingTries: 500
  disableSequenceValidation: false
postgresService:
  postgresDb: ffc-pay-batch-processor-prd
  postgresqlHost: prdffcdbssq1001.postgres.database.azure.com
  postgresPort: 5432
  postgresSchema: public
secretProviderClass:
  azure:
    keyvaultName: PRDFFCINFKV1001
    objects:
      - objectName: prd-ffcahwr-appInsights-connectionString
        objectType: secret
      - objectName: prd-postgresPayBatchProcessorUser
        objectType: secret

  secretObjects:
    - secretName: ffc-pay-batch-processor
      type: Opaque
      data:
        - objectName: prd-ffcahwr-appInsights-connectionString
          key: APPINSIGHTS_CONNECTION_STRING
        - objectName: prd-postgresPayBatchProcessorUser
          key: POSTGRES_USER
