environment: development
name: ffc-sfi-payment-batch-processor
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-payment-batch-processor

labels: {}

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-sfi-payment-batch-processor-config-map

containerSecret:
  name: ffc-sfi-payment-batch-processor-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  # DO NOT have more than 1 replica
  # Payment batch files need to be processed in order
  # So concurrent processing with multiple pods could cause problems
  replicas: 1
  minReplicas: 1
  maxReplicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 100Mi
  requestCpu: 40m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3007
  azureStorageAccountName: sfipayments
  messageQueueHost: namespace.servicebus.windows.net
  paymentTopicAddress: ffc-sfi-payment-request
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false

postgresService:
  postgresDb: ffc_sfi_payment_batch_processor
  postgresExternalName:
  postgresHost: ffc-sfi-payment-batch-processor-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

livenessProbe:
  path: /healthz
  port: 3007
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3007
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

aadPodIdentity: true