name: Version Bump

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  version-bump:
    uses: DEFRA/ffc-shared-actions/.github/workflows/version-bump.yml@main
    with:
      node-version: '24'
#      audit-level: 'critical' - set if you need to override azure-pipelines to pass only critical audit issues
    secrets: inherit